sonar.projectKey=Necrass-Dev_NecrassRs
sonar.organization=necrass-dev
sonar.rust.lcov.reportPaths=target/llvm-cov/lcov.info
sonar.exclusions=target/**,Cargo.lock
sonar.cpd.exclusions=crates/necrassrs-cli/templates/build.rs,crates/necrassrs-cli/templates/main.rs
