[package]
name = "{{name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
necrassrs = { git = "https://github.com/Necrass-Dev/NecrassRs.git", rev = "ffd953c8c56496677f62583f96794396b5f126c9", version = "0.1.0" }
necrassrs-actix = { git = "https://github.com/Necrass-Dev/NecrassRs.git", rev = "ffd953c8c56496677f62583f96794396b5f126c9", version = "0.1.0" }

[build-dependencies]
miette = "7.6.0"
necrassrs-build = { git = "https://github.com/Necrass-Dev/NecrassRs.git", rev = "ffd953c8c56496677f62583f96794396b5f126c9", version = "0.1.0" }

[patch.crates-io]
apollo-compiler = { git = "https://github.com/Necrass-Dev/NecrassRs.git", rev = "ffd953c8c56496677f62583f96794396b5f126c9", version = "1.33.0" }

[workspace]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
